[build]
target = "x86_64-unknown-none"

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]